import About from '@/components/main/About';
import DefaultMainSection from '@/components/main/DefaultMainSection';
import Experiences from '@/components/main/Experiences';
import Projects from '@/components/main/Projects';
import TechStack from '@/components/main/TechStack';
import TopUserProfile from '@/components/main/TopUserProfile';
import { useAppDispatch, useAppSelector } from '@/hooks/redux';
import { UserDoc } from '@/models/user.model';
import { setCurrentUser } from '@/store/user.slice';
import { Flex } from '@chakra-ui/react';
import { SignIn, UserButton, useUser } from '@clerk/nextjs';
import axios from 'axios';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
  const { isSignedIn, isLoaded, user } = useUser();
  const dispatch = useAppDispatch();
  const currentUser = useAppSelector((state) => state.currentUser.user);
  useEffect(() => {
    if (!isSignedIn) return;
    const fetchUser = async () => {
      try {
        const { data: fetchedUser } = await axios.get<UserDoc>(
          '/api/user/user'
        );
        dispatch(setCurrentUser(fetchedUser));
      } catch (err: any) {
        console.log(err);
      }
    };
    fetchUser();
    console.log(currentUser);
  }, [dispatch, isSignedIn]);

  return (
    <>
      <Head>
        <title>Devfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        minH={'full'}
        bg={'black'}
        flexDir={'column'}
        gap={8}
        justifyContent={'flex-start'}
        alignItems={'center'}
        py={16}
      >
        {isSignedIn && <UserButton />}
        {!isSignedIn && <SignIn />}

        {isLoaded && isSignedIn && (
          <Flex flexDir={'column'} gap={12}>
            <TopUserProfile
              userProfileData={{
                fullName: currentUser?.fullName,
                oneLiner: currentUser?.oneLiner,
                socials: currentUser?.socials,
              }}
              clerkUserId={user.id}
            />
            {currentUser?.about !== undefined ? (
              <About />
            ) : (
              <DefaultMainSection sectionTitle={'About'} />
            )}
            {currentUser?.experiences?.length ? (
              <Experiences />
            ) : (
              <DefaultMainSection sectionTitle={'Experiences'} />
            )}
            {currentUser?.techStack?.length ? (
              <TechStack />
            ) : (
              <DefaultMainSection sectionTitle={'Tech Stack'} />
            )}
            {currentUser?.projects?.length ? (
              <Projects />
            ) : (
              <DefaultMainSection sectionTitle={'Projects'} />
            )}
          </Flex>
        )}
      </Flex>
    </>
  );
}
