import DefaultMainSection from '@/components/main/DefaultMainSection';
import TopUserProfile from '@/components/main/TopUserProfile';
import { SignIn, UserButton, useUser } from '@clerk/nextjs';
import axios from 'axios';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
  const user = useUser();

  useEffect(() => {
    if (user.isSignedIn) {
      const sendUser = async () => {
        const { data } = await axios.post<{ userId: string; fullName: string }>(
          'http://localhost:5000/api/auth',
          { userId: user.user?.id, fullName: user.user?.fullName },
          {
            headers: {
              'Content-Type': 'application/json',
            },
          }
        );
        //todo add data to a state
      };
      sendUser();
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Devfolio.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen bg-black flex-col gap-8 justify-start items-center py-16`}
      >
        {user.isSignedIn && <UserButton />}
        {!user.isSignedIn && <SignIn />}

        {user.isSignedIn && (
          <div className="flex flex-col gap-12">
            <TopUserProfile />
            <DefaultMainSection sectionTitle={'About'} />
            <DefaultMainSection sectionTitle={'Experiences'} />
            <DefaultMainSection sectionTitle={'Tech Stack'} />
            <DefaultMainSection sectionTitle={'Projects'} />
          </div>
        )}
      </main>
    </>
  );
}
