import { getIconByLinkName } from '@/components/utils/getIconsByLink';
import { useAppDispatch, useAppSelector } from '@/hooks/redux';
import { axiosClient } from '@/lib/utils/axiosInstance';
import { ExperienceDoc } from '@/models/experience.model';
import { ProjectDoc } from '@/models/project.model';
import { SocialDoc } from '@/models/social.model';
import { TechDoc } from '@/models/tech.model';
import { UserDoc } from '@/models/user.model';
import { setCurrentUser } from '@/store/user.slice';
import {
  Avatar,
  Box,
  Button,
  Code,
  Drawer,
  DrawerBody,
  DrawerCloseButton,
  DrawerContent,
  DrawerOverlay,
  Flex,
  HStack,
  Heading,
  Link,
  Text,
  VStack,
  useDisclosure,
} from '@chakra-ui/react';
import Head from 'next/head';
import { useEffect } from 'react';

import { setExperiences } from '@/store/experiences.slice';
import { setProjects } from '@/store/projects.slice';
import { setSocialLinks } from '@/store/socials.slice';
import { setTechStack } from '@/store/tech.slice';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { Fade } from 'react-awesome-reveal';
import { BsGlobeAmericas } from 'react-icons/bs';
import { FaBars } from 'react-icons/fa';
import { VscGithubAlt } from 'react-icons/vsc';

const Portfolio = () => {
  const router = useRouter();
  const { isOpen, onOpen, onClose } = useDisclosure();
  const dispatch = useAppDispatch();
  const localUserState = useAppSelector((state) => state.currentUser.user);
  const localProjectsState = useAppSelector((state) => state.projects.projects);
  const localExperiencesState = useAppSelector(
    (state) => state.experiences.experiences
  );
  const localSocialsState = useAppSelector((state) => state.socials.socials);
  const localTechStack = useAppSelector((state) => state.techStack.techStack);
  const [profileImgUrl, setProfileImageUrl] = useState('');

  useEffect(() => {
    if (!router.query.userId) return;
    const fetchUserData = async () => {
      try {
        const { data } = await axiosClient.get<{
          mongoUser: UserDoc | null;
          projects: ProjectDoc[];
          experiences: ExperienceDoc[];
          socials: SocialDoc[];
          techStack: TechDoc[];
          clerkUserImage: string;
        }>(`/user/${router.query.userId}`);
        if (!data.mongoUser) return;
        if (data.mongoUser) dispatch(setCurrentUser(data.mongoUser));
        if (data.projects) dispatch(setProjects(data.projects));
        if (data.experiences) dispatch(setExperiences(data.experiences));
        if (data.socials) dispatch(setSocialLinks(data.socials));
        if (data.techStack) dispatch(setTechStack(data.techStack));
        if (data.clerkUserImage) setProfileImageUrl(data.clerkUserImage);
      } catch (err: any) {
        console.log(err);
      }
    };
    fetchUserData();
  }, [dispatch, router.query.userId]);

  return (
    <>
      <Head>
        <title>{`Portfolio ${
          router.query.userId
            ? `| ${localUserState ? localUserState?.fullName : ''}`
            : ''
        }`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        display={{
          base: 'flex',
          sm: 'flex',
          md: 'none',
          lg: 'none',
          xl: 'none',
        }}
        justify={'end'}
      >
        <Button
          _hover={{
            background: 'transparent',
            color: 'pink.200',
          }}
          px={4}
          pt={6}
          bg={'transparent'}
          onClick={onOpen}
        >
          <FaBars />
        </Button>
        {isOpen && (
          <Drawer placement="right" onClose={onClose} isOpen={isOpen}>
            <DrawerOverlay />
            <DrawerContent bg={'black'}>
              <DrawerCloseButton
                _hover={{
                  background: 'transparent',
                  color: 'pink.200',
                }}
                _focus={{ outline: 'none' }}
              />
              <DrawerBody
                display={'flex'}
                justifyContent={'center'}
                alignItems={'center'}
              >
                <VStack spacing={10} align="center">
                  {localUserState?.about && localUserState.about !== '' ? (
                    <Link onClick={onClose} href="#about">
                      <Code
                        bgClip={'text'}
                        bgGradient="linear(to-r, white, orange.400)"
                      >
                        About
                      </Code>
                    </Link>
                  ) : null}
                  {localTechStack && localTechStack?.length !== 0 ? (
                    <Link onClick={onClose} href="#tech">
                      <Code
                        bgClip={'text'}
                        bgGradient="linear(to-r, white, orange.400)"
                      >
                        Tech Stack
                      </Code>
                    </Link>
                  ) : null}
                  {localExperiencesState?.length !== 0 ? (
                    <Link onClick={onClose} href="#experience">
                      <Code
                        bgClip={'text'}
                        bgGradient="linear(to-r, white, orange.400)"
                      >
                        Experiences
                      </Code>
                    </Link>
                  ) : null}
                  {localProjectsState?.length !== 0 ? (
                    <Link onClick={onClose} href="#projects">
                      <Code
                        bgClip={'text'}
                        bgGradient="linear(to-r, white, orange.400)"
                      >
                        Projects
                      </Code>
                    </Link>
                  ) : null}
                </VStack>
              </DrawerBody>
            </DrawerContent>
          </Drawer>
        )}
      </Flex>
      <Flex
        display={{
          base: 'none',
          md: 'flex',
          lg: 'flex',
          xl: 'flex',
          sm: 'none',
        }}
        pt={8}
        px={8}
        gap={8}
        justifyContent={'end'}
      >
        {localUserState?.about && localUserState.about !== '' ? (
          <Link href="#about">
            <Code bgClip={'text'} bgGradient="linear(to-r, bisque, cyan.300)">
              About
            </Code>
          </Link>
        ) : null}
        {localTechStack && localTechStack?.length !== 0 ? (
          <Link href="#tech">
            <Code bgClip={'text'} bgGradient="linear(to-r, bisque, cyan.300)">
              Tech Stack
            </Code>
          </Link>
        ) : null}
        {localExperiencesState?.length !== 0 ? (
          <Link href="#experience">
            <Code bgClip={'text'} bgGradient="linear(to-r, bisque, cyan.300)">
              Experiences
            </Code>
          </Link>
        ) : null}
        {localProjectsState?.length !== 0 ? (
          <Link href="#projects">
            <Code bgClip={'text'} bgGradient="linear(to-r, bisque, cyan.300)">
              Projects
            </Code>
          </Link>
        ) : null}
      </Flex>

      <Flex
        minH={'full'}
        flexDir={'column'}
        gap={8}
        justifyContent={'flex-start'}
        alignItems={'center'}
        py={16}
      >
        <Flex
          flexDir={'column'}
          gap={12}
          minW={['100%', 'xl']}
          maxW={['100%', '2xl']}
          px={[4, 8]}
        >
          {localUserState?.fullName ? (
            <Flex gap={4} position={'relative'} alignItems={'center'}>
              <Avatar
                variant="square"
                loading="lazy"
                size="xl"
                src={profileImgUrl}
                name={localUserState!.fullName}
              />
              <Heading
                bgClip={'text'}
                bgGradient="linear(to-r, gray.300, pink.200)"
                fontSize={'2xl'}
              >
                {localUserState?.fullName}
              </Heading>
            </Flex>
          ) : null}

          {localSocialsState?.length !== 0 ? (
            <Flex
              display={{
                base: 'none',
                sm: 'none',
                md: 'flex',
                lg: 'flex',
              }}
              gap={4}
              flexDir={'column'}
              alignItems={'flex-start'}
            >
              <Flex gap={4}>
                {localSocialsState.map((social) => (
                  <Link
                    key={social._id}
                    href={social.url}
                    color={'blue.100'}
                    target={'_blank'}
                    fontSize={'xl'}
                    _hover={{
                      textDecoration: 'none',
                      color: '#0cee08',
                      mt: '-2',
                      transition: 'all 400ms',
                    }}
                  >
                    {getIconByLinkName(social.name)}
                  </Link>
                ))}
              </Flex>
              {localUserState?.oneLiner ? (
                <Text
                  bgGradient="linear(to-r, gray.400, gray.100)"
                  bgClip="text"
                  cursor={'default'}
                >
                  {localUserState?.oneLiner}
                </Text>
              ) : null}
            </Flex>
          ) : null}

          {localUserState?.about && localUserState.about !== '' ? (
            <Fade cascade>
              <Flex id="about" gap={2} flexDir={'column'}>
                <Heading
                  bgClip={'text'}
                  bgGradient="linear(to-r, blue.300, white)"
                  fontSize={'2xl'}
                >
                  About
                </Heading>
                <Text
                  bgGradient="linear(to-r, gray.300, gray.200)"
                  bgClip="text"
                  cursor={'default'}
                >
                  {localUserState?.about}.
                </Text>
              </Flex>
            </Fade>
          ) : null}
          {localTechStack && localTechStack?.length !== 0 ? (
            <Flex
              id="tech"
              whiteSpace={'pre-wrap'}
              wrap={'wrap'}
              flexDir={'column'}
              gap={4}
            >
              <Heading
                bgClip={'text'}
                bgGradient="linear(to-r, blue.300, white)"
                fontSize={'2xl'}
              >
                Tech Stack
              </Heading>
              <Flex wrap={'wrap'} flexDir={'row'} gap={2}>
                {localTechStack.map((tech) => (
                  <Code
                    bg={'transparent'}
                    size={'xs'}
                    mr={1}
                    bgClip={'text'}
                    bgGradient="linear(to-r, yellow.300, blue.100)"
                    key={tech._id}
                  >
                    {tech.name}
                  </Code>
                ))}
              </Flex>
            </Flex>
          ) : null}

          {localExperiencesState && localExperiencesState?.length !== 0 ? (
            <Flex id="experiences" flexDir={'column'} gap={4}>
              <Heading
                bgClip={'text'}
                bgGradient="linear(to-r, blue.300, white)"
                fontSize={'2xl'}
              >
                Experiences
              </Heading>
              <>
                {localExperiencesState.map((experience) => (
                  <Box
                    whiteSpace={'pre'}
                    gap={4}
                    p={8}
                    key={experience._id}
                    cursor={'default'}
                    my={2}
                  >
                    <Flex whiteSpace={'pre-wrap'} gap={2} flexDir={'column'}>
                      <Flex
                        gap={12}
                        alignItems={'flex-start'}
                        justifyContent={'start'}
                      >
                        <Heading
                          bgClip={'text'}
                          bgGradient="linear(to-r, gray.300, gray.300)"
                          fontWeight={'bold'}
                          alignSelf={'flex-start'}
                          fontSize={'md'}
                        >
                          {experience.companyName}
                        </Heading>

                        <Flex gap={1} flexDir={'column'}>
                          <Heading
                            bgClip={'text'}
                            bgGradient="linear(to-r, gray.400, white)"
                            fontSize={'sm'}
                          >
                            {experience.position}
                          </Heading>
                          <Code
                            bgClip={'text'}
                            bgGradient="linear(to-r, blue.300, green.300)"
                            fontSize={'sm'}
                          >
                            {experience.startDate
                              ? `${new Date(
                                  experience.startDate
                                ).toLocaleString('default', {
                                  month: 'long',
                                })} ${new Date(
                                  experience.startDate
                                ).getFullYear()}`
                              : null}
                            -
                            {experience.present === false
                              ? `${new Date(experience.endDate).toLocaleString(
                                  'default',
                                  {
                                    month: 'long',
                                  }
                                )} ${new Date(
                                  experience.endDate
                                ).getFullYear()}`
                              : 'Present'}
                          </Code>
                          <Text
                            fontSize={'sm'}
                            color={'gray.500'}
                            fontStyle={'italic'}
                          >
                            {experience.description}
                          </Text>
                        </Flex>
                      </Flex>
                    </Flex>
                  </Box>
                ))}
              </>
            </Flex>
          ) : null}

          {localProjectsState ? (
            <Flex id="projects" flexDir={'column'} gap={4}>
              <Heading
                bgClip={'text'}
                bgGradient="linear(to-r, blue.300, white)"
                fontSize={'2xl'}
              >
                Projects
              </Heading>
              {localProjectsState.map((project) => (
                <Box
                  key={project._id}
                  cursor={'default'}
                  _hover={{
                    borderColor: 'gray.800',
                  }}
                  transition="border-color 400ms"
                  borderColor={'gray.700'}
                  borderWidth={'1px'}
                  borderRadius={'xl'}
                  borderStyle={'solid'}
                  my={2}
                >
                  <Flex m={2} p={4} flexDir={'column'}>
                    <Flex justifyContent={'space-between'}>
                      <Heading color={'gray.300'} size={'md'}>
                        {project.title}
                      </Heading>

                      <HStack>
                        {project?.demoLink ? (
                          <Link target="_blank" href={project?.demoLink}>
                            <BsGlobeAmericas />
                          </Link>
                        ) : null}
                        <Link
                          target="_blank"
                          rel="noopener noreferer"
                          href={project?.githubLink}
                        >
                          <VscGithubAlt />
                        </Link>
                      </HStack>
                    </Flex>

                    <Text
                      fontStyle={'italic'}
                      my={4}
                      color={'gray.500'}
                      size={'xs'}
                    >
                      {project?.description}
                    </Text>

                    <Flex
                      maxW={'1/2'}
                      wrap={'wrap'}
                      flexDir={'row-reverse'}
                      justifyContent={'space-between'}
                    >
                      <Flex mt={1}>
                        {project?.techStack
                          ? project.techStack.map((tech) => (
                              <Code
                                bg={'transparent'}
                                size={'xs'}
                                mr={1}
                                bgClip={'text'}
                                bgGradient="linear(to-r, yellow.300, blue.300)"
                                key={Math.random()}
                              >
                                {tech}
                              </Code>
                            ))
                          : null}
                      </Flex>
                    </Flex>
                  </Flex>
                </Box>
              ))}
            </Flex>
          ) : null}

          {localSocialsState?.length !== 0 ? (
            <Flex
              display={{
                base: 'flex',
                sm: 'flex',
                md: 'none',
                lg: 'none',
              }}
              gap={4}
              flexDir={'column'}
              alignItems={'center'}
              justifyContent={'center'}
            >
              <Flex gap={4}>
                {localSocialsState.map((social) => (
                  <Link
                    key={social._id}
                    href={social.url}
                    color={'blue.100'}
                    target={'_blank'}
                    fontSize={'2xl'}
                    _hover={{
                      textDecoration: 'none',
                      color: '#0cee08',
                      mt: '-2',
                      transition: 'all 400ms',
                    }}
                  >
                    {getIconByLinkName(social.name)}
                  </Link>
                ))}
              </Flex>
              {localUserState?.oneLiner ? (
                <Text
                  bgGradient="linear(to-r, gray.400, gray.100)"
                  bgClip="text"
                  cursor={'default'}
                >
                  {localUserState?.oneLiner}
                </Text>
              ) : null}
            </Flex>
          ) : null}
        </Flex>
      </Flex>
    </>
  );
};

export default Portfolio;
